steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/flaskhelloworldapp-457910/flaskhelloworldapp', '.']
  # args: ['build', '--platform=linux/amd64', '-t', 'gcr.io/flaskhelloworldapp-457910/flaskhelloworldapp', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/flaskhelloworldapp-457910/flaskhelloworldapp']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'flaskhelloworldapp', '--image', 'gcr.io/flaskhelloworldapp-457910/flaskhelloworldapp', '--region', 'us-central1', '--platform', 'managed','--port','80']
images:
- gcr.io/flaskhelloworldapp-457910/flaskhelloworldapp